[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mets-mods2tei"
version = "0.1.6"
description = "Convert digital documents in METS/MODS format to TEI"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["dependencies", "optional-dependencies"]
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [
    {name = "Kay-Michael Würzner", email = "kay-michael.wuerzner@slub-dresden.de"}
]
maintainers = [
    {name = "Robert Sachunsky", email = "robert.sachunsky@slub-dresden.de"}
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Text Processing :: Markup :: XML",
]

[project.scripts]
mm2tei = "mets_mods2tei.scripts.mets_mods2tei:cli"
mm-update = "mets_mods2tei.scripts.update:cli"

[project.urls]
Homepage = "https://github.com/slub/mets-mods2tei"
Repository = "https://github.com/slub/mets-mods2tei.git"
Issues = "https://github.com/slub/mets-mods2tei/issues"

[tool.setuptools.packages.find]
exclude = ["tests*", "docs*"]

[tool.setuptools.package-data]
mets_mods2tei = ["data/tei_skeleton.xml", "data/iso15924-utf8-20180827.txt"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {test = { file = ["requirements-test.txt"] }}

[tool.ruff]
line-length = 120
indent-width = 4
extend-exclude = ["tests", "*_generateds.py", ".#*"]

[tool.ruff.lint]
ignore = ["DTZ005"]

[tool.ruff.format]
indent-style = "space"
quote-style = "preserve"
line-ending = "auto"
docstring-code-line-length = "dynamic"
